### ISSUE TITLE
"'npm' is not recognized as an internal or external command, operable program or batch file"

### ISSUE THREAD

**Issue by jlbruno** [keithamus/parallelshell#1]
Trying to use this to run multiple tasks as defined here:
http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

I want to run browser-sync and sass at the same time. Here's my scripts portion of my package.json

```
  "scripts": {
    "prestart": "npm install",
    "start": "parallelshell 'npm run watch:browser-sync' 'npm run watch:sass'",
    "watch:browser-sync": "browser-sync start --proxy portal --files 'Web/static/css/*.css' & sass --watch sass:css",
    "watch:sass": "sass --watch Web/static/sass:Web/static/css"
  },
```

When I run "npm start" I can see it tries to run the parallelshell command but it errors out. 

> parallelshell 'npm run watch:browser-sync' 'npm run watch:sass'

''npm' is not recognized as an internal or external command,
operable program or batch file.
`'npm` failed with exit code 1

Unsure if this is due to the new version of npm or if I'm doing something wrong. Any insights?

Thanks

**Comment by olowoseun** [comment]
I'll just stick to using double quotes whenever I'm working in a scripting environment on Windows! &#x1F609;
