### ISSUE TITLE
Question: why not use shell builtins?

### ISSUE THREAD

**Issue by philer** [keithamus/parallelshell#15]
Honest question: How is this different from
`command1 & command2 & command3` ?

Regards – philer

**Comment by keithamus** [comment]
Hey @philer thanks for the issue.

We had a discussion about this in #5. Hopefully this will provide some good context for you.

Abridged is:

 - `&` creates a background process, which only exits if you kill it or it ends. parallelshell will autokill processes if one of the others dies.
 - Your example (`command1 & command2 & command3`) will wait in the terminal until command3 ends only. parallelshell will wait until all 3 end.
 - In your example, if command1/command2 exit with non-zero exit code, then this will not effect the outcome of your shell (i.e. they can fail and npm/bash/whatever will ignore it). parallelshell will not ignore it, and will exit with the first non-zero exit code.
 - In your example, pressing `Ctrl+C` will exit `command3` but not 1/2. parallelshell will exit all 3
 - parallelshell outputs all jobs stdout/err to its stdout/err. background jobs do that... kind of coincidentally (read: unreliably)
 - You could use `wait` to alleviate _some_ of these issues, but `wait` does not solve them all, and is not available in Windows (as far as I know)

If you don't need the above, feel free to use `&` or `wait`. If you need all of the above, use parallelshell :smile:

**Comment by philer** [comment]
I see. Should have searched the issues first.
Thanks for your answer, I can see now how your tool could be helpful. :)
