### ISSUE TITLE
Clarify purpose of module

### ISSUE THREAD

**Issue by nichoth** [keithamus/parallelshell#20]
Is it only for cross-platform scripts?

Or is it different than this bash syntax:
    
    $ cmd1 & cmd2 & cmd3

**Comment by keithamus** [comment]
He @nichoth thanks for the issue.

See #5 and #15. To quote:

>
 - `&` creates a background process, which only exits if you kill it or it ends. parallelshell will autokill processes if one of the others dies.
 - Your example (`command1 & command2 & command3`) will wait in the terminal until command3 ends only. parallelshell will wait until all 3 end.
 - In your example, if command1/command2 exit with non-zero exit code, then this will not effect the outcome of your shell (i.e. they can fail and npm/bash/whatever will ignore it). parallelshell will not ignore it, and will exit with the first non-zero exit code.
 - In your example, pressing `Ctrl+C` will exit `command3` but not 1/2. parallelshell will exit all 3
 - parallelshell outputs all jobs stdout/err to its stdout/err. background jobs do that... kind of coincidentally (read: unreliably)
 - You could use `wait` to alleviate _some_ of these issues, but `wait` does not solve them all, and is not available in Windows (as far as I know)
>
If you don't need the above, feel free to use `&` or `wait`. If you need all of the above, use parallelshell :smile: 

If you'd like to take my words and write them more succinctly into the README, and raise a PR, I'd most definitely merge it with much gratitude.
