### ISSUE TITLE
run command then parallelshell commands

### ISSUE THREAD

**Issue by janusch** [keithamus/parallelshell#26]
Hey Keith,
Great blog post, thank you for inspiring me to remove gulp/grunt from my build process!!!

I just have one problem when using parallelshell; maybe you could help me to get it to work?

My use case:
clean a folder then start two processes with parallelshell, they are webpack and browser-sync.

My script looks like this: `"start": "npm run clean && parallelshell 'npm run dev_watch' 'npm run dev'"`

this runs all the processes, but browser-sync does not pickup the changes.
When i run `"start": "parallelshell 'npm run dev_watch' 'npm run dev'"` it woks just fine.

How could I run the clean task once at start and still get the other tasks to work properly?

I tried it synchronously   `"start": " run clean & parallelshell 'npm run dev_watch' 'npm run dev'"` with the same unfulfilling result as the parallel one.

Thanks for your great work again!
Maybe you can shed some light on this for me.

**Comment by keithamus** [comment]
Hey @janusch thanks for the issue.

Your first line should work fine. When you say "browser-sync does not pickup the changes" could you elaborate more?

**Comment by janusch** [comment]
@keithamus thanks for your quick reply!

browser-sync is like live reload, so it should recognized files changed by webpack and reload the browser. Somehow webpack repackages and browser-sync does nothing. This only occurs when the clean task is part of the script, otherwise it works fine.
For now I am using `"start": "parallelshell 'npm run dev_watch' 'npm run dev'"` this script and do not clean the folder on start anymore. I would prefer to clean before though.

I am not sure how to elaborate more, there is no error or log, sorry.

**Comment by keithamus** [comment]
Why not run `npm run clean` before running `npm run dev`? e.g.

```json
"start": "parallelshell 'npm run dev_watch' 'npm run clean && npm run dev'"
```

**Comment by janusch** [comment]
Thank you for looking into it!
I tried your proposed solution, but for whatever reason browser-sync does not trigger.

I think ill just keep the clean task out of the start script and go with `"start": "parallelshell 'npm run dev_watch' 'npm run dev'"` 
I'll just run the clean script when i need it.

Btw, there is one thing that I am missing without gulp, maybe you have an idea on how to do that with a script. It is the gulp-inject task, where you can inject file references into an html file. This is useful for browser cache busting, I add a hash when the file changes.

Thanks again for your help!

**Comment by keithamus** [comment]
I typically use a templating language, such as [Handlebars](http://handlebarsjs.com/) and pass the template some JSON (either through the cli if it allows it, otherwise I'll write a bit of JS). This is generally much more flexible than something like gulp-inject, and scales well for when your project gets bigger. 

See https://github.com/keithamus/npm-scripts-example/blob/master/package.json#L36 for an example of this.

If you really want to stick with gulp-inject style regexp replacement, then try keithamus/npm-scripts-example#22

**Comment by paulpflug** [comment]
could be a problem of browser-sync.
Maybe it watches for file changes, but when the file gets deleted the watcher vanishes also. The only workaround is to watch the whole folder and filter the change events..

I had a similar problem when a file watcher didn't fire on changes of a compiled js file for the same reason. When compiling from coffeescript, the js gets deleted and the watcher too :smile:

**Comment by janusch** [comment]
Interesting, @paulpflug thanks for your reply!
I think with this we can safely close this issue.
