### ISSUE TITLE
process.argv.slice(2) not working for single quotes

### ISSUE THREAD

**Issue by FacioRatio** [keithamus/parallelshell#32]
Trying this script:

"dev": "parallelshell 'npm run livereload -s' 'npm run serve -s' 'npm run watch -s'"

Yields the following errors:
''npm' is not recognized as an internal or external command, operable program or batch file.
'run' is not recognized as an internal or external command, operable program or batch file.
'livereload' is not recognized as an internal or external command, operable program or batch file.
''npm' is not recognized as an internal or external command, operable program or batch file.
'run' is'  not recognized as an internal or external command, operable program or batch file.
'serve' is not recognized as an internal or external command, operable program or batch file.
''npm' is not recognized as an internal or external command, operable program or batch file.
'run' is not recognized as an internal or external command, operable program or batch file.

As you can see, it's ignoring the quotes and just treating everything separated by whitespace as a separate command.

I'm on Windows 10 Command Prompt and Parallelshell 2.0. I get the same results from the command line when I use single quotes. It works fine from the command line with double quotes.

**Comment by keithamus** [comment]
Hey @FacioRatio thanks for the issue.

You'll need to use double quotes in Windows. You can escape them in the json, like so:

```json
"dev": "parallelshell \"npm run livereload -s\" \"npm run serve -s\" \"npm run watch -s\""
```

If this doesn't help, let me know and we'll re-open the issue.

**Comment by FacioRatio** [comment]
That works fine, thanks. And thanks for your "How to Use npm as a Build Tool" post; my build is so much simpler now without Gulp.

**Comment by keithamus** [comment]
:tada: :smile:
