### ISSUE TITLE
with --wait, parallelshell always exits with 0?

### ISSUE THREAD

**Issue by kentor** [keithamus/parallelshell#38]
Even if the subprocesses have an exit code > 0. Is this intended?

**Comment by keithamus** [comment]
That sounds like a bug. Have you tried using the dev branch (see #30)? If it fixes it for you, let me know and we can look to merging #30.

**Comment by kentor** [comment]
Master:
```bash
❯ npm start; echo $?

> @ start /Users/kenneth/stuff/parallelshell-test
> parallelshell --wait 'rm asdf'

rm: asdf: No such file or directory
0
```
exits 0.

Dev:
```bash
❯ npm start; echo $?

> @ start /Users/kenneth/stuff/parallelshell-test
> parallelshell --wait 'rm asdf'

0
```

exits 0. does not show the failed rm message?

**Comment by divmgl** [comment]
I can confirm that `parallelshell` is exiting with 0 when `--wait` is specified. I have a script that is throwing an error and `parallelshell` does not stay open. This is on Mac OSX.
