### ISSUE TITLE
Issue with assigning variables

### ISSUE THREAD

**Issue by davesnx** [keithamus/parallelshell#45]
``` bash
parallelshell "echo 1" "ENV=3"
```

Hello,
You can't declare variables, I guess that is because isn't a process (?). I'm not sure if it's an issue or not. 
The use case for that is you want to define some env variables at the same time of running a process.
i.e.

``` bash
NODE_ENV=dev node server.js
```

_**Edit:**_ Reading the code I'm figuring out what's going on, the child-process spawn is throwing an error.

**Comment by paulpflug** [comment]
I think, this should work:

```
parallelshell "ENV=3 echo 1"
```

**Comment by davesnx** [comment]
@paulpflug isn't working, it's the same error

**Comment by paulpflug** [comment]
basically parallelshell does a `sh -c "command"`
when I call `sh -c "TEST=test env"`, TEST is there but `sh -c "TEST=test echo $TEST"` doesn't print anything

seems it is a problem of echo, maybe it computes its own env?

**Comment by davesnx** [comment]
I don't think so... when u call `sh -c "ENV"` shows all the ENV of the system
Also, when u run `parallelshell "TEST=test"`throws and error of sh

**Comment by paulpflug** [comment]
"TEST=test" should only work for the following command if you want to 
export to ENV then you have to use "export", but parallelshell doesn't 
support ENV exchange between different commands.


Am 21. Februar 2016 1:48:50 nachm. schrieb David Sancho 
<notifications@github.com>:
