### ISSUE TITLE
Same argument passed to all shells? 

### ISSUE THREAD

**Issue by tim-field** [keithamus/parallelshell#54]
In my npm scripts I've got something like this

```
    "js:build:dev": "parallelshell 'npm run js:build:renter -- -d' 'npm run js:build:manage -- -d' 'npm run js:build:blog -- -d' 'npm run js:build:cms -- -d'",
    "js:build": "parallelshell 'npm run js:build:renter' 'npm run js:build:manage' 'npm run js:build:blog' 'npm run js:build:cms'",
```

Where `js:build:dev` is passing the `-d` param to each sub script.

It'd be really nice if I could instead have

```
   "js:build:dev": "npm run js:build -- -d",
    "js:build": "parallelshell 'npm run js:build:renter' 'npm run js:build:manage' 'npm run js:build:blog' 'npm run js:build:cms'",
```

And have that `-d` passed down into each script.  

If you don't think this is a silly idea I could take a shot at a pull request, but I might need a pointer as to where to look.

**Comment by keithamus** [comment]
@tim-field it's a good suggestion, but `parallelshell` is effectively deprecated in favour of [`npm-run-all`](https://github.com/mysticatea/npm-run-all). I'd recommend switching to that, which will support exactly what you're after, much more succinctly to boot:

```json
"js:build-dev": "npm run js:build -- -d",
"js:build": "npm run all js:build:* --"
```

Feel free to continue using `parallelshell` if you'd like, but sadly I won't be accepting any PRs.
