### ISSUE TITLE
fails on node8

### ISSUE THREAD

**Issue by gabor** [keithamus/parallelshell#56]
basically #49 

TypeError: "cwd" must be a string
    at normalizeSpawnArguments (child_process.js:380:11)
    at exports.spawn (child_process.js:465:38)
    at ....node_modules/parallelshell/index.js:104:17

**Comment by adamreisnz** [comment]
Also experiencing this unfortunately

**Comment by MeanTeam** [comment]
Ups! I create a new issue with this.
I solved modifying this line:
`cwd: process.cwd(),`

**Comment by darkguy2008** [comment]
Fixed! See https://github.com/keithamus/parallelshell/issues/57#issuecomment-306351280
