### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by PatrickHeneise** [keithamus/parallelshell#62]
> Latest 2.0.0; 6 commits to master since this release

@keithamus there seems to be inconsistencies with GitHub releases and what is on npm?

**Comment by keithamus** [comment]
I think my token got invalidated for the auto-release mechanism. @darkguy2008 is the current maintainer of this; @darkguy2008 do you want to manually add the release notes entries?

**Comment by darkguy2008** [comment]
@keithamus oh huh, go figure! Sure, I actually have to merge some PRs and tidy up the npm package as well which I'll do around this weekend as I'm using the package too. Is that something related to what I'm talking about or are those notes somewhere else? thanks :)

**Comment by keithamus** [comment]
Yeah - I guess theres some incosnsistencies between https://github.com/keithamus/parallelshell/releases and https://github.com/keithamus/parallelshell/blob/master/History.md as well? e.g. "Releases" has 2.0 but History.md doesnt, but History.md has 3.0 and 3.0.1 while Releases doesn't?

To be frank, this is entirely your project now 😄 so whatever direction you take with any of this I'm completely okay with 👍

**Comment by keithamus** [comment]
In fact if you'd like to we can move it to under your username or perhaps an organisation?

**Comment by darkguy2008** [comment]
@keithamus oh right, that makes sense, I've updated History and npm but not the /releases page. I see, I'm a bit new regarding public projects in GitHub (or at least with a nice userbase, haha) but I'll do my best 😄 .

That's good to know and it's also a honor 😃  I don't have an organization yet so either way could work 👍
