### ISSUE TITLE
Preserving colorized output

### ISSUE THREAD

**Issue by danawoodman** [keithamus/parallelshell#7]
Very cool package. One thing I'd love to see is the preservation of colored terminal output. Right now the color is stripped out. Would this be something that is possible to add in?

**Comment by keithamus** [comment]
Thanks @danawoodman for the issue. Parallelshell should just pipe the output down without issue - so should support colour fine. What are you seeing, no colours or loads of gibberish? If no colours it could be some kind of colour detection from the program you're using - which we should be able to trick into showing colours. What program are you using that is not showing colours?

**Comment by danawoodman** [comment]
Thanks for the quick reply!

I'm seeing the following when running `parrallelshell 'mocha'`:

![with parrallelshell](http://cl.ly/ZapM/Screen%20Shot%202015-02-02%20at%204.28.43%20PM.png)

...where as if I run Mocha directly I get:

![without parrallelshell](http://cl.ly/ZapM/Screen%20Shot%202015-02-02%20at%204.28.43%20PM.png)

I'm using iTerm2 to display the output.

**Comment by keithamus** [comment]
Seems like mocha is checking `tty.isatty(1) && tty.isatty(2)` in the [base reporter](https://github.com/mochajs/mocha/blob/53c414462460c743174c492ad7a0b75f887e74d8/lib/reporters/base.js#L24-L36). I believe we'd just need to trick it into believing that parallelshell's stdin and out are ttys.

**Comment by danawoodman** [comment]
@keithamus would using `spawn` work instead of exec?

**Comment by keithamus** [comment]
Deployed as `v1.1.0`

**Comment by danawoodman** [comment]
Yay! :+1:

**Comment by danawoodman** [comment]
I'm now getting the following exception locally:

```bash
$ ./node_modules/parallelshell/index.js
./node_modules/parallelshell/index.js: line 1: use strict: command not found
./node_modules/parallelshell/index.js: line 2: syntax error near unexpected token `('
./node_modules/parallelshell/index.js: line 2: `var spawn = require('child_process').spawn;'
```

Any thoughts?

**Comment by danawoodman** [comment]
Nevermind, I was running it directly on the command line rather than running through Node
